### ISSUE TITLE
Dependency issues on pronto 0.9.5 with rainbow

### ISSUE THREAD

**Issue by jalyna** [aergonaut/pronto-goodcheck#1]
Thank you for this nice little gem 😃 

![screen shot 2018-10-19 at 11 14 02](https://user-images.githubusercontent.com/5362483/47209615-0dcc1f80-d391-11e8-9595-613e2f450714.png)

As a workaround I needed to use the latest version of pronto directly from Github (as it is in the Gemfile here). I think it would be helpful to add a section to the README.md as long as the latest pronto version is not released.

**Comment by aergonaut** [comment]
Sorry for the super late response, but Pronto has released a 0.10.0 version that resolves the rainbow conflict. Please update Pronto to resolve!
